/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TiermakerImport } from './routes/tiermaker'
import { Route as PollsImport } from './routes/polls'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TiermakerRoute = TiermakerImport.update({
  path: '/tiermaker',
  getParentRoute: () => rootRoute,
} as any)

const PollsRoute = PollsImport.update({
  path: '/polls',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/polls': {
      id: '/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof PollsImport
      parentRoute: typeof rootRoute
    }
    '/tiermaker': {
      id: '/tiermaker'
      path: '/tiermaker'
      fullPath: '/tiermaker'
      preLoaderRoute: typeof TiermakerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PollsRoute,
  TiermakerRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/polls",
        "/tiermaker"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/polls": {
      "filePath": "polls.tsx"
    },
    "/tiermaker": {
      "filePath": "tiermaker.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
